### PR TITLE
Issue #290: Description field size is changed from 'String' to 'Text' in C_Order table

### PR DESCRIPTION
**Pull request by tomyrodeghiero**
EPL-1214: The field reference type in C_Order table change from 'String' to 'Text'

### CODE REVIEW

**Comment by Gremiger** [comment]
Is this PR ok? Because the description doesn't match with the entirety of the changelist

**Comment by tomyrodeghiero** [comment]
> Is this PR ok? Because the description doesn't match with the entirety of the changelist

It is not okay. When I executed **export.database**, it brought in many changes that shouldn't have been impacted. I will soon commit to removing the unnecessary changes because I wasn't aware that there were changes that shouldn't be uploaded. I thought these were the correct ones. Thank you for letting me know.

**Comment by valenvivaldi** [comment]
Always remember to check carefully what is added to the git stage before committing.

**Comment by tomyrodeghiero** [comment]
> Always remember to check carefully what is added to the git stage before committing.

@valenvivaldi  I completely agree. I thought the changes I was uploading (since it was the only thing I modified in **export.database**, and I had a clean tree of changes before running it) were fine. Thank you very much for the advice, I agree that it's essential to do it before committing

@isaiasb-etendo will soon provide me with a command to clean up the things that shouldn't have been uploaded

**Review by isaiasb-etendo — APPROVED** [review]

**Review by valenvivaldi — APPROVED** [review]

**Review by Gremiger — APPROVED** [review]

**Pull request merged**
